name: Deploy Snapshot

on:
  push:
    branches:
      - feat/publishable

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install Node.js dependencies
        run: yarn install --immutable
      - name: Build Process
        run: yarn build
      - name: Publish Package to NPM
        run: |
          yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
          yarn npm publish
