name: Create PR Release and Deploy

on:
  push:
    branches:
      - main
      - hotfix/**

permissions:
  contents: write
  pull-requests: write

jobs:
  pr:
    name: Create Release PR or Ship Release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.rp.outputs.release_created }}
      prs_created: ${{ steps.rp.outputs.prs_created }}
    timeout-minutes: 30
    steps:
      - name: Get Variables
        run: |
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
      - name: Checkout Repo
        uses: actions/checkout@v4
      - id: rp
        name: Determine either pr or publish
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          target-branch: ${{ github.ref_name }}
  deploy:
    needs: pr
    if: ${{ needs.pr.outputs.release_created != 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      LOWERCASE_REPO: ''
    steps:
      - uses: ssistoza/rp-node-poc/.github/workflows/deploy-to-environment.yml
        with:
          env: dev
          tag_version: main
  package:
    name: Publish to NPM
    needs: pr
    if: ${{ needs.pr.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install Node.js dependencies
        run: yarn install --immutable
      - name: Build Process
        run: yarn build
      - name: Publish Package to NPM
        run: "echo 'Publishing to NPM' Test"
